# FROM allows us to take an image someone else built
FROM nginx

# COPY tells docker that we want to take index.html and package it into the image
# and put it into a specific location.
COPY index.html /usr/share/nginx/html
